"""Add profile fields

Revision ID: 2b2738e5c4af
Revises: 764aee2ac6b2
Create Date: 2026-03-29 04:11:29.427555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2b2738e5c4af'
down_revision: Union[str, None] = '764aee2ac6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_company_profile_id', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'company_profiles', ['company_profile_id'], ['id'])
    op.alter_column('roadmaps', 'roadmap_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('idx_roadmaps_field', table_name='roadmaps')
    op.drop_index('idx_roadmaps_user_id', table_name='roadmaps')
    op.drop_index('ix_roadmaps_difficulty_level', table_name='roadmaps')
    op.drop_index('ix_roadmaps_title', table_name='roadmaps')
    op.add_column('students', sa.Column('resume_base64', sa.String(), nullable=True))
    op.add_column('students', sa.Column('resume_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('job_type', sa.String(), nullable=True))
    op.drop_column('users', 'is_company_profile_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_company_profile_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('students', 'job_type')
    op.drop_column('students', 'resume_name')
    op.drop_column('students', 'resume_base64')
    op.create_index('ix_roadmaps_title', 'roadmaps', ['title'], unique=False)
    op.create_index('ix_roadmaps_difficulty_level', 'roadmaps', ['difficulty_level'], unique=False)
    op.create_index('idx_roadmaps_user_id', 'roadmaps', ['user_id'], unique=False)
    op.create_index('idx_roadmaps_field', 'roadmaps', ['field'], unique=False)
    op.alter_column('roadmaps', 'roadmap_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_jobs_company_profile_id', 'jobs', 'company_profiles', ['company_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
