"""sync_all_schema_changes

Revision ID: 7da82da0abe5
Revises: b5c6d7e8f9a0
Create Date: 2026-04-11 09:38:45.764210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7da82da0abe5'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('source_prompt', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_roadmaps_roadmap_key'), 'generated_roadmaps', ['roadmap_key'], unique=True)
    op.drop_table('admin_jobs')
    op.alter_column('applications', 'agent_applied',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_applications_job', table_name='applications')
    op.drop_index('idx_applications_status', table_name='applications')
    op.drop_index('idx_applications_student', table_name='applications')
    op.drop_index('idx_roadmaps_field', table_name='roadmaps')
    op.drop_index('idx_roadmaps_user_id', table_name='roadmaps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_roadmaps_user_id', 'roadmaps', ['user_id'], unique=False)
    op.create_index('idx_roadmaps_field', 'roadmaps', ['field'], unique=False)
    op.create_index('idx_applications_student', 'applications', ['student_id'], unique=False)
    op.create_index('idx_applications_status', 'applications', ['status'], unique=False)
    op.create_index('idx_applications_job', 'applications', ['job_id'], unique=False)
    op.alter_column('applications', 'agent_applied',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('admin_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('posted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('package_lpa', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('application_deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.TEXT(), server_default=sa.text("'Full-time'::text"), autoincrement=False, nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('min_cgpa', sa.NUMERIC(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('apply_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_logo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('openings', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], name='admin_jobs_posted_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_jobs_pkey')
    )
    op.drop_index(op.f('ix_generated_roadmaps_roadmap_key'), table_name='generated_roadmaps')
    op.drop_table('generated_roadmaps')
    # ### end Alembic commands ###
