"""Add roadmap table

Revision ID: add_roadmap_table
Revises: 
Create Date: 2026-03-24 11:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'add_roadmap_table'
down_revision: Union[str, None] = '9725b1674e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS roadmaps (
            id SERIAL NOT NULL,
            user_id UUID,
            field VARCHAR(255) NOT NULL DEFAULT '',
            title VARCHAR(500) NOT NULL DEFAULT '',
            description TEXT,
            role VARCHAR NOT NULL,
            skills TEXT NOT NULL,
            roadmap_data JSON NOT NULL,
            difficulty_level VARCHAR(50),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            generated_by VARCHAR(100),
            usage_count BIGINT,
            last_accessed TIMESTAMP WITH TIME ZONE,
            is_public VARCHAR(10),
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_roadmaps_id ON roadmaps (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_roadmaps_role ON roadmaps (role)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_roadmaps_user_id ON roadmaps (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_roadmaps_field ON roadmaps (field)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmaps_field'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_role'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
