"""add_field_to_roadmaps

Revision ID: f2a3b4c5d6e7
Revises: add_roadmap_table
Create Date: 2026-03-26 23:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a3b4c5d6e7'
down_revision: Union[str, None] = 'add_roadmap_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the missing 'field' column to roadmaps table
    op.add_column('roadmaps', sa.Column('field', sa.String(length=255), nullable=False, server_default=''))
    
    # Add index for field column
    op.create_index(op.f('ix_roadmaps_field'), 'roadmaps', ['field'], unique=False)
    
    # Add other missing columns from the model
    op.add_column('roadmaps', sa.Column('title', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('roadmaps', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('difficulty_level', sa.String(length=50), nullable=True))
    op.add_column('roadmaps', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('roadmaps', sa.Column('usage_count', sa.BigInteger(), nullable=True, server_default='0'))
    op.add_column('roadmaps', sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roadmaps', sa.Column('is_public', sa.String(length=10), nullable=True, server_default='true'))
    
    # Add indexes for new columns
    op.create_index(op.f('ix_roadmaps_title'), 'roadmaps', ['title'], unique=False)
    op.create_index(op.f('ix_roadmaps_difficulty_level'), 'roadmaps', ['difficulty_level'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_roadmaps_difficulty_level'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_title'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_field'), table_name='roadmaps')
    
    # Drop columns
    op.drop_column('roadmaps', 'is_public')
    op.drop_column('roadmaps', 'last_accessed')
    op.drop_column('roadmaps', 'usage_count')
    op.drop_column('roadmaps', 'generated_by')
    op.drop_column('roadmaps', 'difficulty_level')
    op.drop_column('roadmaps', 'description')
    op.drop_column('roadmaps', 'title')
    op.drop_column('roadmaps', 'field')
    # ### end Alembic commands ###
